dist: xenial
language: cpp
compiler: clang
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:  
  - curl -T ip_filter-0.0.1-Linux.deb -uyellowcoffee:$API_KEY "https://api.bintray.com/content/yellowcoffee/HomeWork2/HomeWork2/1/ip_filter-0.0.1-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
